import { 
  TreePine, 
  ShieldCheck, 
  HardHat, 
  Axe, 
  Truck, 
  ClipboardCheck, 
  Phone, 
  Clock,
  CheckCircle2,
  AlertTriangle,
  ArrowRight,
  Camera,
  Quote,
  MessageCircle,
  XCircle,
  FileWarning,
  Zap,
  Leaf,
  Home,
  Hammer,
  CloudLightning
} from 'lucide-react';

export const Icons = {
  Tree: TreePine,
  Shield: ShieldCheck,
  Helmet: HardHat,
  Axe: Axe,
  Truck: Truck,
  Checklist: ClipboardCheck,
  Phone: Phone,
  Clock: Clock,
  Check: CheckCircle2,
  Alert: AlertTriangle,
  ArrowRight: ArrowRight,
  Camera: Camera,
  Quote: Quote,
  WhatsApp: MessageCircle,
  Close: XCircle,
  Warning: FileWarning,
  Zap: Zap,
  Leaf: Leaf,
  Home: Home,
  Hammer: Hammer,
  Storm: CloudLightning
};